services:
  ttp.medtechchain.nl:
    build:
      context: .
      dockerfile: Dockerfile
    image: medtechchain/ttp
    container_name: ttp.medtechchain.nl
    environment:
      ENCRYPT_BINARY: "/app/lib/encrypt"
      STORE_DIR_PATH: "/app/lib/store"
    ports:
      - "6000:6000"
    volumes:
      - store:/app/lib/store

volumes:
  store: